services:
  backend:
    build:
      context: ./backend
    image: kcube-boilerplate-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:devenv@kcube-database:5432/kcube-boilerplate-db
    restart: no
    container_name: kcube-backend
    networks:
      - kcube-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    image: kcube-boilerplate-frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    restart: no
    container_name: kcube-frontend
    networks:
      - kcube-network

  db:
      image: postgres:16-alpine
      container_name: kcube-database
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=devenv
        - POSTGRES_DB=kcube-boilerplate-db
      ports:
        - "5433:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./database_schema.sql:/docker-entrypoint-initdb.d/schema.sql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 1s
        timeout: 10s
        retries: 20
      networks:
        - kcube-network

volumes:
  pgdata:

networks:
  kcube-network:
    driver: bridge
